name: Lint and test

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        node-version: [10, 12]

    steps:
      - uses: actions/checkout@v1
      - name: Lint and test with ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm ci, build, lint and test
        run: |
          npm ci
          npm run compile
          npm run lint
          npm test
        env:
          CI: true
      - name: run and print version
        run: |
          npm link
          elm-language-server --version
